# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.15

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/wangzhenkui/cproj/naruto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/wangzhenkui/cproj/naruto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wangzhenkui/cproj/naruto/CMakeFiles /Users/wangzhenkui/cproj/naruto/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/wangzhenkui/cproj/naruto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named naruto

# Build rule for target.
naruto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 naruto
.PHONY : naruto

# fast build rule for target.
naruto/fast:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/build
.PHONY : naruto/fast

#=============================================================================
# Target rules for targets named ut

# Build rule for target.
ut: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ut
.PHONY : ut

# fast build rule for target.
ut/fast:
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/build
.PHONY : ut/fast

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

clients/c++/connection.o: clients/c++/connection.cpp.o

.PHONY : clients/c++/connection.o

# target to build an object file
clients/c++/connection.cpp.o:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/clients/c++/connection.cpp.o
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/clients/c++/connection.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/clients/c++/connection.cpp.o
.PHONY : clients/c++/connection.cpp.o

clients/c++/connection.i: clients/c++/connection.cpp.i

.PHONY : clients/c++/connection.i

# target to preprocess a source file
clients/c++/connection.cpp.i:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/clients/c++/connection.cpp.i
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/clients/c++/connection.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/clients/c++/connection.cpp.i
.PHONY : clients/c++/connection.cpp.i

clients/c++/connection.s: clients/c++/connection.cpp.s

.PHONY : clients/c++/connection.s

# target to generate assembly for a file
clients/c++/connection.cpp.s:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/clients/c++/connection.cpp.s
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/clients/c++/connection.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/clients/c++/connection.cpp.s
.PHONY : clients/c++/connection.cpp.s

clients/c++/connection_pool.o: clients/c++/connection_pool.cpp.o

.PHONY : clients/c++/connection_pool.o

# target to build an object file
clients/c++/connection_pool.cpp.o:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/clients/c++/connection_pool.cpp.o
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/clients/c++/connection_pool.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/clients/c++/connection_pool.cpp.o
.PHONY : clients/c++/connection_pool.cpp.o

clients/c++/connection_pool.i: clients/c++/connection_pool.cpp.i

.PHONY : clients/c++/connection_pool.i

# target to preprocess a source file
clients/c++/connection_pool.cpp.i:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/clients/c++/connection_pool.cpp.i
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/clients/c++/connection_pool.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/clients/c++/connection_pool.cpp.i
.PHONY : clients/c++/connection_pool.cpp.i

clients/c++/connection_pool.s: clients/c++/connection_pool.cpp.s

.PHONY : clients/c++/connection_pool.s

# target to generate assembly for a file
clients/c++/connection_pool.cpp.s:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/clients/c++/connection_pool.cpp.s
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/clients/c++/connection_pool.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/clients/c++/connection_pool.cpp.s
.PHONY : clients/c++/connection_pool.cpp.s

clients/example/c++/example.o: clients/example/c++/example.cpp.o

.PHONY : clients/example/c++/example.o

# target to build an object file
clients/example/c++/example.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/clients/example/c++/example.cpp.o
.PHONY : clients/example/c++/example.cpp.o

clients/example/c++/example.i: clients/example/c++/example.cpp.i

.PHONY : clients/example/c++/example.i

# target to preprocess a source file
clients/example/c++/example.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/clients/example/c++/example.cpp.i
.PHONY : clients/example/c++/example.cpp.i

clients/example/c++/example.s: clients/example/c++/example.cpp.s

.PHONY : clients/example/c++/example.s

# target to generate assembly for a file
clients/example/c++/example.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/clients/example/c++/example.cpp.s
.PHONY : clients/example/c++/example.cpp.s

cluster.o: cluster.cpp.o

.PHONY : cluster.o

# target to build an object file
cluster.cpp.o:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/cluster.cpp.o
.PHONY : cluster.cpp.o

cluster.i: cluster.cpp.i

.PHONY : cluster.i

# target to preprocess a source file
cluster.cpp.i:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/cluster.cpp.i
.PHONY : cluster.cpp.i

cluster.s: cluster.cpp.s

.PHONY : cluster.s

# target to generate assembly for a file
cluster.cpp.s:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/cluster.cpp.s
.PHONY : cluster.cpp.s

connect_worker.o: connect_worker.cpp.o

.PHONY : connect_worker.o

# target to build an object file
connect_worker.cpp.o:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/connect_worker.cpp.o
.PHONY : connect_worker.cpp.o

connect_worker.i: connect_worker.cpp.i

.PHONY : connect_worker.i

# target to preprocess a source file
connect_worker.cpp.i:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/connect_worker.cpp.i
.PHONY : connect_worker.cpp.i

connect_worker.s: connect_worker.cpp.s

.PHONY : connect_worker.s

# target to generate assembly for a file
connect_worker.cpp.s:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/connect_worker.cpp.s
.PHONY : connect_worker.cpp.s

global.o: global.cpp.o

.PHONY : global.o

# target to build an object file
global.cpp.o:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/global.cpp.o
.PHONY : global.cpp.o

global.i: global.cpp.i

.PHONY : global.i

# target to preprocess a source file
global.cpp.i:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/global.cpp.i
.PHONY : global.cpp.i

global.s: global.cpp.s

.PHONY : global.s

# target to generate assembly for a file
global.cpp.s:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/global.cpp.s
.PHONY : global.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/main.cpp.s
.PHONY : main.cpp.s

naruto.o: naruto.cpp.o

.PHONY : naruto.o

# target to build an object file
naruto.cpp.o:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/naruto.cpp.o
.PHONY : naruto.cpp.o

naruto.i: naruto.cpp.i

.PHONY : naruto.i

# target to preprocess a source file
naruto.cpp.i:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/naruto.cpp.i
.PHONY : naruto.cpp.i

naruto.s: naruto.cpp.s

.PHONY : naruto.s

# target to generate assembly for a file
naruto.cpp.s:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/naruto.cpp.s
.PHONY : naruto.cpp.s

net/connector.o: net/connector.cpp.o

.PHONY : net/connector.o

# target to build an object file
net/connector.cpp.o:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/net/connector.cpp.o
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/net/connector.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/net/connector.cpp.o
.PHONY : net/connector.cpp.o

net/connector.i: net/connector.cpp.i

.PHONY : net/connector.i

# target to preprocess a source file
net/connector.cpp.i:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/net/connector.cpp.i
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/net/connector.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/net/connector.cpp.i
.PHONY : net/connector.cpp.i

net/connector.s: net/connector.cpp.s

.PHONY : net/connector.s

# target to generate assembly for a file
net/connector.cpp.s:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/net/connector.cpp.s
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/net/connector.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/net/connector.cpp.s
.PHONY : net/connector.cpp.s

protocol/message.pb.o: protocol/message.pb.cc.o

.PHONY : protocol/message.pb.o

# target to build an object file
protocol/message.pb.cc.o:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/protocol/message.pb.cc.o
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/protocol/message.pb.cc.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/protocol/message.pb.cc.o
.PHONY : protocol/message.pb.cc.o

protocol/message.pb.i: protocol/message.pb.cc.i

.PHONY : protocol/message.pb.i

# target to preprocess a source file
protocol/message.pb.cc.i:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/protocol/message.pb.cc.i
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/protocol/message.pb.cc.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/protocol/message.pb.cc.i
.PHONY : protocol/message.pb.cc.i

protocol/message.pb.s: protocol/message.pb.cc.s

.PHONY : protocol/message.pb.s

# target to generate assembly for a file
protocol/message.pb.cc.s:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/protocol/message.pb.cc.s
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/protocol/message.pb.cc.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/protocol/message.pb.cc.s
.PHONY : protocol/message.pb.cc.s

s_connect.o: s_connect.cpp.o

.PHONY : s_connect.o

# target to build an object file
s_connect.cpp.o:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/s_connect.cpp.o
.PHONY : s_connect.cpp.o

s_connect.i: s_connect.cpp.i

.PHONY : s_connect.i

# target to preprocess a source file
s_connect.cpp.i:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/s_connect.cpp.i
.PHONY : s_connect.cpp.i

s_connect.s: s_connect.cpp.s

.PHONY : s_connect.s

# target to generate assembly for a file
s_connect.cpp.s:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/s_connect.cpp.s
.PHONY : s_connect.cpp.s

unittest/ut_main.o: unittest/ut_main.cpp.o

.PHONY : unittest/ut_main.o

# target to build an object file
unittest/ut_main.cpp.o:
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/unittest/ut_main.cpp.o
.PHONY : unittest/ut_main.cpp.o

unittest/ut_main.i: unittest/ut_main.cpp.i

.PHONY : unittest/ut_main.i

# target to preprocess a source file
unittest/ut_main.cpp.i:
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/unittest/ut_main.cpp.i
.PHONY : unittest/ut_main.cpp.i

unittest/ut_main.s: unittest/ut_main.cpp.s

.PHONY : unittest/ut_main.s

# target to generate assembly for a file
unittest/ut_main.cpp.s:
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/unittest/ut_main.cpp.s
.PHONY : unittest/ut_main.cpp.s

utils/bytes.o: utils/bytes.cpp.o

.PHONY : utils/bytes.o

# target to build an object file
utils/bytes.cpp.o:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/utils/bytes.cpp.o
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/utils/bytes.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/utils/bytes.cpp.o
.PHONY : utils/bytes.cpp.o

utils/bytes.i: utils/bytes.cpp.i

.PHONY : utils/bytes.i

# target to preprocess a source file
utils/bytes.cpp.i:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/utils/bytes.cpp.i
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/utils/bytes.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/utils/bytes.cpp.i
.PHONY : utils/bytes.cpp.i

utils/bytes.s: utils/bytes.cpp.s

.PHONY : utils/bytes.s

# target to generate assembly for a file
utils/bytes.cpp.s:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/utils/bytes.cpp.s
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/utils/bytes.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/utils/bytes.cpp.s
.PHONY : utils/bytes.cpp.s

utils/errors.o: utils/errors.cpp.o

.PHONY : utils/errors.o

# target to build an object file
utils/errors.cpp.o:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/utils/errors.cpp.o
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/utils/errors.cpp.o
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/utils/errors.cpp.o
.PHONY : utils/errors.cpp.o

utils/errors.i: utils/errors.cpp.i

.PHONY : utils/errors.i

# target to preprocess a source file
utils/errors.cpp.i:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/utils/errors.cpp.i
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/utils/errors.cpp.i
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/utils/errors.cpp.i
.PHONY : utils/errors.cpp.i

utils/errors.s: utils/errors.cpp.s

.PHONY : utils/errors.s

# target to generate assembly for a file
utils/errors.cpp.s:
	$(MAKE) -f CMakeFiles/naruto.dir/build.make CMakeFiles/naruto.dir/utils/errors.cpp.s
	$(MAKE) -f CMakeFiles/ut.dir/build.make CMakeFiles/ut.dir/utils/errors.cpp.s
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/utils/errors.cpp.s
.PHONY : utils/errors.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... naruto"
	@echo "... ut"
	@echo "... client"
	@echo "... clients/c++/connection.o"
	@echo "... clients/c++/connection.i"
	@echo "... clients/c++/connection.s"
	@echo "... clients/c++/connection_pool.o"
	@echo "... clients/c++/connection_pool.i"
	@echo "... clients/c++/connection_pool.s"
	@echo "... clients/example/c++/example.o"
	@echo "... clients/example/c++/example.i"
	@echo "... clients/example/c++/example.s"
	@echo "... cluster.o"
	@echo "... cluster.i"
	@echo "... cluster.s"
	@echo "... connect_worker.o"
	@echo "... connect_worker.i"
	@echo "... connect_worker.s"
	@echo "... global.o"
	@echo "... global.i"
	@echo "... global.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... naruto.o"
	@echo "... naruto.i"
	@echo "... naruto.s"
	@echo "... net/connector.o"
	@echo "... net/connector.i"
	@echo "... net/connector.s"
	@echo "... protocol/message.pb.o"
	@echo "... protocol/message.pb.i"
	@echo "... protocol/message.pb.s"
	@echo "... s_connect.o"
	@echo "... s_connect.i"
	@echo "... s_connect.s"
	@echo "... unittest/ut_main.o"
	@echo "... unittest/ut_main.i"
	@echo "... unittest/ut_main.s"
	@echo "... utils/bytes.o"
	@echo "... utils/bytes.i"
	@echo "... utils/bytes.s"
	@echo "... utils/errors.o"
	@echo "... utils/errors.i"
	@echo "... utils/errors.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

